export interface IUserPartnerInfo{
    partner_min_age: number,
    partner_max_age: number,
	partner_bodyColor: string,
	partner_min_height: number,
	partner_max_height: number,
	partner_min_weight: number,
	partner_max_weight: number,
	partner_education: string,
	partner_islamic_education: string,
	partner_salah: string,
	partner_hajab_maintain: number,
	partner_religious: boolean,
	partner_marital_status: string,
	partner_coutry: string,
	partner_state: string,
}