export { default as logo } from './images/logo.png';
export { default as logoBgRemove } from './images/logo-removebg.png';
export { default as muslim } from './images/muslim.png';
export { default as signUp } from './images/signUp.png';
export { default as support } from './images/callCenter.png';
export { default as hello } from './images/hello.png';
export { default as location } from './images/location.png';
export { default as weight } from './images/weight.png';
export { default as color } from './images/color.png';
export { default as job } from './images/job.png';
export { default as education } from './images/education.png';
export { default as imam } from './images/imam.png';
export { default as family } from './images/family.png';
export { default as muslimLove } from './images/muslimLove.png';
export { default as welcome } from './images/Welcome.png';
export { default as noR } from './images/noR.png';
// export {default as refreshSound} from "./music/refresh.wav";
// export {default as defaultUser} from "./images/defaultUser.jpg";
// export {default as defaultUser} from "./images/defaultUser.jpg";
